mykey = "petclinic"
ami = "ami-00ca32bbc84273381"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "petclinic-jenkins-server-secgr"
jenkins-server-tag = "Jenkins Server of Petclinic"
jenkins-profile = "petclinic-jenkins-profile-tr"
jenkins-role = "petclinic-jenkins-server-role"
